from .types import ResumeCertification, ResumeData, ResumeEducation, ResumeExperience

DUMMY_RESUME_DATA: dict[str, ResumeData] = {
    "ai_agent_developer": ResumeData(
        name="Liam Gallagher",
        title="AI Agent Developer | Product & Data Engineer",
        email="liam.g.ai@email.com",
        phone="555-678-9012",
        linkedin_url="linkedin.com/in/liamgallagherai",
        professional_summary="Innovative and entrepreneurial engineer with a foundational background in data engineering and analytics, complemented by 3 years of hands-on experience building and shipping commercial Shopify applications. Now intensely focused on designing and building autonomous AI agents using LangChain, LangGraph, and the OpenAI API. Seeking to leverage a unique blend of data architecture, product development sense, and cutting-edge AI skills to create practical, intelligent automation solutions.",
        experience=[
            ResumeExperience(
                title="Founder / Lead Developer (Entrepreneurial Venture)",
                company="North Peak Digital",
                location="Remote",
                start_date="June 2021",
                end_date="July 2024",
                points=[
                    "Independently designed, built, and launched two successful Shopify applications, acquiring over 1,500 active paying users.",
                    "Engineered the full stack using Python (Flask), JavaScript, and the Shopify API to create robust, customer-facing tools.",
                    "Managed all aspects of the product lifecycle, from initial concept and user research to deployment, marketing, and customer support.",
                    "Gained deep experience in API integration, background job processing, and building reliable, scalable web services.",
                ],
            ),
            ResumeExperience(
                title="Data Engineer",
                company="Global Consumer Goods Corp.",
                location="Cincinnati, OH",
                start_date="January 2018",
                end_date="May 2021",
                points=[
                    "Led the technical design and implementation of the marketing department's first centralized data warehouse in Amazon Redshift.",
                    "Built and automated ETL pipelines using Python and SQL to ingest data from disparate sources including Nielsen, Salesforce, and internal transaction systems.",
                    "As a data analyst, created dashboards in Tableau that provided insights into brand performance and campaign ROI, directly influencing marketing spend.",
                    "Collaborated with business stakeholders to translate their requirements into technical specifications for data models and reports.",
                ],
            ),
        ],
        education=[
            ResumeEducation(
                degree="Bachelor of Science",
                major="Information Systems",
                institution="The Ohio State University",
                grad_date="December 2017",
            )
        ],
        skills=[
            # AI & Agentic Systems (Most Important - List First)
            "AI Agent & Tool Development",
            "LangChain & LangGraph",
            "OpenAI API (GPT-4, Embeddings)",
            "Retrieval-Augmented Generation (RAG)",
            "Vector Databases (ChromaDB)",
            "Prompt Engineering",
            # Engineering & Development
            "Python (Flask, Pandas)",
            "REST API Design & Integration",
            "JavaScript (React, Node.js)",
            "Shopify API",
            "Git",
            "Docker",
            # Data & Analytics
            "Advanced SQL",
            "Data Warehousing (Redshift)",
            "ETL/ELT Pipeline Development",
            "Tableau",
            "AWS (S3, Redshift, Lambda)",
        ],
        certifications=[
            ResumeCertification(
                title="DeepLearning.AI - LangChain for LLM Application Development",
                date="May 2024",
            )
        ],
    ),
    "data_scientist": ResumeData(
        name="Eleanor Vance",
        title="Senior Data Scientist",
        email="eleanor.vance@email.com",
        phone="555-123-4567",
        linkedin_url="linkedin.com/in/eleanorvance",
        professional_summary="Results-driven Senior Data Scientist with over 8 years of experience in applying machine learning, statistical modeling, and data analysis to solve complex business problems. Proven ability to lead data-driven initiatives from concept to execution, delivering actionable insights that drive revenue growth and operational efficiency. Expert in Python, R, SQL, and cloud-based data platforms.",
        experience=[
            ResumeExperience(
                title="Senior Data Scientist",
                company="Innovatech Solutions Inc.",
                location="San Francisco, CA",
                start_date="January 2020",
                end_date="Present",
                points=[
                    "Developed and deployed a customer churn prediction model using XGBoost, reducing monthly churn by 15% and saving an estimated $1.2M annually.",
                    "Led a team of 3 junior analysts to build a real-time anomaly detection system for financial transactions, decreasing fraudulent activity by 25%.",
                    "Engineered data pipelines using Apache Airflow and AWS services (S3, Redshift, EC2) to process over 10TB of data daily, improving data availability by 40%.",
                    "Created and presented data visualizations and dashboards in Tableau to C-level executives, translating complex findings into strategic business recommendations.",
                ],
            ),
            ResumeExperience(
                title="Data Scientist",
                company="DataDriven Co.",
                location="Boston, MA",
                start_date="June 2017",
                end_date="December 2019",
                points=[
                    "Built a recommendation engine using collaborative filtering techniques, which increased user engagement by 20% and cross-sell revenue by 12%.",
                    "Performed A/B testing and statistical analysis to optimize marketing campaign performance, resulting in a 30% improvement in conversion rates.",
                    "Automated reporting processes with Python scripts, saving 20+ hours of manual work per week for the analytics team.",
                ],
            ),
        ],
        education=[
            ResumeEducation(
                degree="Master of Science",
                major="Data Science",
                institution="Stanford University",
                grad_date="May 2017",
            ),
            ResumeEducation(
                degree="Bachelor of Science",
                major="Computer Science",
                institution="University of California, Berkeley",
                grad_date="May 2015",
            ),
        ],
        skills=[
            "Python",
            "R",
            "SQL",
            "Pandas",
            "NumPy",
            "Scikit-learn",
            "TensorFlow",
            "PyTorch",
            "XGBoost",
            "Git",
            "Docker",
            "AWS (S3, EC2, Redshift)",
            "Azure",
            "Apache Spark",
            "Apache Airflow",
            "Tableau",
            "Power BI",
            "Statistical Modeling",
            "Machine Learning",
            "Data Visualization",
            "A/B Testing",
        ],
        certifications=[
            ResumeCertification(
                title="AWS Certified Machine Learning - Specialty", date="June 2022"
            ),
            ResumeCertification(title="Google Professional Data Engineer", date="August 2021"),
        ],
    ),
    "software_developer": ResumeData(
        name="Marcus Rivera",
        title="Full-Stack Software Developer",
        email="m.rivera.dev@email.com",
        phone="555-987-6543",
        linkedin_url="linkedin.com/in/marcusrivera",
        professional_summary="Creative and detail-oriented Full-Stack Developer with 5+ years of experience building and maintaining responsive web applications from the ground up. Proficient in JavaScript, React, Node.js, and modern DevOps practices. Passionate about writing clean, efficient code and collaborating in fast-paced Agile environments to deliver high-quality software solutions.",
        experience=[
            ResumeExperience(
                title="Software Engineer",
                company="NextGen Innovations",
                location="Austin, TX",
                start_date="July 2021",
                end_date="Present",
                points=[
                    "Architected and developed a new client-facing dashboard using React and Redux, improving user session length by 30%.",
                    "Built and maintained RESTful APIs with Node.js and Express, serving over 1 million requests per day with 99.9% uptime.",
                    "Implemented a CI/CD pipeline using Jenkins and Docker, reducing deployment time from 2 hours to 15 minutes.",
                    "Collaborated with a team of 5 developers to migrate legacy monolithic application to a microservices architecture, improving scalability and system resilience.",
                ],
            ),
            ResumeExperience(
                title="Junior Web Developer",
                company="Digital Craft Agency",
                location="Austin, TX",
                start_date="May 2019",
                end_date="June 2021",
                points=[
                    "Developed responsive and interactive user interfaces for client websites using HTML5, CSS3, and vanilla JavaScript.",
                    "Assisted senior developers in building e-commerce solutions with React, contributing to a 20% increase in online sales for a key client.",
                    "Identified and fixed over 200 bugs in existing codebases, enhancing application stability and user experience.",
                ],
            ),
        ],
        education=[
            ResumeEducation(
                degree="Bachelor of Science",
                major="Computer Science",
                institution="Texas A&M University",
                grad_date="May 2019",
            )
        ],
        skills=[
            "JavaScript (ES6+)",
            "TypeScript",
            "HTML5 & CSS3",
            "React.js",
            "Redux",
            "Node.js",
            "Express.js",
            "Python",
            "RESTful APIs",
            "GraphQL",
            "PostgreSQL",
            "MongoDB",
            "Git & GitHub",
            "Docker",
            "CI/CD (Jenkins)",
            "AWS (EC2, S3, Lambda)",
            "Jest & React Testing Library",
            "Agile/Scrum Methodologies",
            "Webpack",
            "Next.js",
        ],
        certifications=[
            ResumeCertification(title="AWS Certified Developer - Associate", date="November 2023")
        ],
    ),
    "digital_marketing_manager": ResumeData(
        name="Sophia Chen",
        title="Digital Marketing Manager",
        email="sophia.chen.mktg@email.com",
        phone="555-345-6789",
        linkedin_url="linkedin.com/in/sophiachen",
        professional_summary="Dynamic and data-driven Digital Marketing Manager with over 7 years of experience developing and executing comprehensive online marketing strategies. Proven track record of increasing brand awareness, lead generation, and ROI through effective management of SEO, SEM, content marketing, and social media campaigns. Adept at leveraging marketing analytics to drive continuous improvement and achieve key business objectives.",
        experience=[
            ResumeExperience(
                title="Digital Marketing Manager",
                company="Bright-Peak Financial",
                location="Chicago, IL",
                start_date="August 2020",
                end_date="Present",
                points=[
                    "Directed a multi-channel digital strategy that increased organic search traffic by 150% and generated a 40% uplift in qualified marketing leads in two years.",
                    "Managed an annual digital advertising budget of $500k across Google Ads and LinkedIn, optimizing campaigns to decrease CPA by 22% while increasing conversion rates by 18%.",
                    "Led a content marketing initiative that included blog posts, whitepapers, and webinars, resulting in over 50,000 new email subscribers.",
                    "Analyzed campaign performance and user behavior using Google Analytics and HubSpot, providing actionable insights to the sales and product development teams.",
                ],
            ),
            ResumeExperience(
                title="Marketing Specialist",
                company="Vantage Apparel",
                location="Chicago, IL",
                start_date="June 2017",
                end_date="July 2020",
                points=[
                    "Executed daily social media operations across Instagram, Facebook, and Twitter, growing the total audience by over 200,000 followers.",
                    "Coordinated email marketing campaigns using Mailchimp, achieving an average open rate of 25% and a 4% click-through rate.",
                    "Conducted keyword research and on-page SEO optimizations that contributed to a 60% increase in organic traffic.",
                ],
            ),
        ],
        education=[
            ResumeEducation(
                degree="Bachelor of Business Administration",
                major="Marketing",
                institution="University of Illinois Urbana-Champaign",
                grad_date="May 2017",
            )
        ],
        skills=[
            "Search Engine Optimization (SEO)",
            "Search Engine Marketing (SEM)",
            "Pay-Per-Click (PPC) Advertising",
            "Content Strategy & Creation",
            "Social Media Marketing",
            "Email Marketing Automation",
            "Campaign Management",
            "Conversion Rate Optimization (CRO)",
            "Google Analytics",
            "Google Ads",
            "HubSpot",
            "Salesforce Marketing Cloud",
            "SEMrush",
            "Ahrefs",
            "Mailchimp",
            "Data Analysis & Reporting",
        ],
        certifications=[
            ResumeCertification(title="Google Ads Search Certification", date="October 2023"),
            ResumeCertification(title="HubSpot Inbound Marketing Certified", date="January 2023"),
        ],
    ),
    "data_analyst": ResumeData(
        name="Isabella Rossi",
        title="Senior Data Analyst",
        email="isabella.rossi.da@email.com",
        phone="555-456-7890",
        linkedin_url="linkedin.com/in/isabellarossi",
        professional_summary="Detail-oriented Senior Data Analyst with 6 years of experience transforming complex datasets into actionable business intelligence. Expertise in SQL, Python, and data visualization tools like Tableau and Power BI. Proven ability to conduct in-depth analysis, create intuitive dashboards, and present findings to stakeholders to support strategic decision-making and identify opportunities for growth.",
        experience=[
            ResumeExperience(
                title="Senior Data Analyst",
                company="QuantumLeap Analytics",
                location="New York, NY",
                start_date="May 2021",
                end_date="Present",
                points=[
                    "Leads the development of interactive Tableau dashboards to track key performance indicators (KPIs) for the sales department, providing insights that led to a 15% increase in cross-sell opportunities.",
                    "Performs complex cohort and funnel analyses using SQL and Python (Pandas) to understand user behavior, presenting findings that informed a major redesign of the customer onboarding process.",
                    "Mentors two junior analysts, providing guidance on analytical best practices, SQL query optimization, and effective data storytelling.",
                    "Collaborates with data engineering to define data requirements and ensure the integrity of data in the enterprise data warehouse.",
                ],
            ),
            ResumeExperience(
                title="Data Analyst",
                company="MarketPulse Inc.",
                location="New York, NY",
                start_date="June 2018",
                end_date="April 2021",
                points=[
                    "Extracted and cleaned data from various sources using SQL to support ad-hoc reporting requests from the marketing team.",
                    "Designed and maintained weekly performance reports in Excel and Power BI, saving 10+ hours of manual reporting effort per week.",
                    "Conducted A/B testing analysis for email campaigns, which resulted in a 5% improvement in click-through rates.",
                    "Assisted in the documentation of data dictionaries and business logic.",
                ],
            ),
        ],
        education=[
            ResumeEducation(
                degree="Bachelor of Science",
                major="Statistics",
                institution="New York University (NYU)",
                grad_date="May 2018",
            )
        ],
        skills=[
            "Advanced SQL",
            "Python (Pandas, NumPy)",
            "R",
            "Tableau Desktop",
            "Microsoft Power BI",
            "Advanced Microsoft Excel",
            "Statistical Analysis",
            "A/B Testing",
            "Data Warehousing Concepts",
            "Business Intelligence (BI)",
            "Data Storytelling",
            "Requirements Gathering",
        ],
        certifications=[
            ResumeCertification(title="Tableau Desktop Certified Associate", date="March 2022"),
            ResumeCertification(
                title="Microsoft Certified: Power BI Data Analyst Associate", date="July 2021"
            ),
        ],
    ),
    "ai_engineer_transition": ResumeData(
        name="David Chen",
        title="AI Engineer | Data Engineer",
        email="david.chen.ai@email.com",
        phone="555-567-8901",
        linkedin_url="linkedin.com/in/davidchenai",
        professional_summary="Accomplished Data Engineer with a strong background in building scalable data pipelines and distributed systems. Currently transitioning into AI Engineering, leveraging a deep understanding of data architecture to build and deploy robust machine learning systems. Passionate about MLOps, large language models (LLMs), and creating the infrastructure that powers intelligent applications.",
        experience=[
            ResumeExperience(
                title="Data Engineer",
                company="Cognitive Cloud Solutions",
                location="Seattle, WA",
                start_date="April 2020",
                end_date="Present",
                points=[
                    "Designed and built the infrastructure for a production recommendation engine, including feature stores and model deployment APIs using FastAPI and Docker.",
                    "Developed an MLOps pipeline using MLflow and Kubernetes to automate the training, versioning, and deployment of machine learning models.",
                    "Engineered scalable ETL/ELT pipelines using Apache Spark and Airflow on the AWS cloud, processing terabytes of data daily.",
                    "Architected a data lake on AWS S3 and a data warehouse using Redshift, serving as the single source of truth for analytics and ML teams.",
                ],
            ),
            ResumeExperience(
                title="Software Engineer (Data)",
                company="Streamline Data Corp.",
                location="Seattle, WA",
                start_date="July 2018",
                end_date="March 2020",
                points=[
                    "Developed and maintained data processing jobs using Python and SQL in a large-scale data environment.",
                    "Managed real-time data ingestion pipelines using Apache Kafka.",
                    "Collaborated with analysts to provide clean, structured datasets for reporting and BI dashboards.",
                ],
            ),
        ],
        education=[
            ResumeEducation(
                degree="Bachelor of Science",
                major="Computer Engineering",
                institution="University of Washington",
                grad_date="June 2018",
            )
        ],
        skills=[
            "Python (Advanced)",
            "SQL",
            "Apache Spark",
            "Docker",
            "Kubernetes",
            "MLOps (MLflow, Kubeflow)",
            "CI/CD (Jenkins, GitHub Actions)",
            "AWS (S3, EC2, Glue, Lambda)",
            "GCP (BigQuery, GKE)",
            "Apache Airflow",
            "Apache Kafka",
            "Vector Databases (Pinecone)",
            "LangChain",
            "PyTorch",
            "Scikit-learn",
            "FastAPI",
        ],
        certifications=[
            ResumeCertification(
                title="AWS Certified Machine Learning - Specialty", date="February 2024"
            ),
            ResumeCertification(title="Google Professional Data Engineer", date="May 2022"),
        ],
    ),
}
