"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";

import { resumesAPI } from "@/lib/api/resumes";
import type { ResumeVersionEvent } from "@resume/database/types";

/**
 * Data required to create a resume version from the UI.
 * The hook handles job_id lookup and version_index is auto-generated by the API.
 */
export interface CreateResumeVersionData {
  resume_json: string;
  template_name: string;
  event_type: ResumeVersionEvent;
  parent_version_id?: number | null;
  created_by_user_id: number;
}

/**
 * Hook to fetch resume versions for a job.
 */
export function useResumeVersions(jobId: number) {
  return useQuery({
    queryKey: ["resumes", jobId, "versions"],
    queryFn: () => resumesAPI.listVersionsByJob(jobId),
    enabled: !!jobId,
  });
}

/**
 * Hook to fetch current resume for a job.
 */
export function useCurrentResume(jobId: number) {
  return useQuery({
    queryKey: ["resumes", jobId, "current"],
    queryFn: () => resumesAPI.getCurrentOrNull(jobId),
    enabled: !!jobId,
  });
}

/**
 * Hook to fetch a specific resume version.
 */
export function useResumeVersion(jobId: number, versionId: number) {
  return useQuery({
    queryKey: ["resumes", jobId, "versions", versionId],
    queryFn: async () => {
      const version = await resumesAPI.getVersion(jobId, versionId);
      if (!version) {
        throw new Error("Version not found");
      }
      return version;
    },
    enabled: !!jobId && !!versionId,
  });
}

/**
 * Hook to create a new resume version.
 */
export function useCreateResumeVersion() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (params: { jobId: number; data: CreateResumeVersionData }) => {
      // First, get or create the resume for this job
      try {
        const resume = await resumesAPI.getCurrent(params.jobId);
        // Create the version - the API handles job_id lookup and version_index
        return resumesAPI.createVersion(resume.id, {
          ...params.data,
          job_id: params.jobId,
          version_index: 0, // Will be overwritten by the API
        });
      } catch {
        // No resume exists for this job yet; create the first version
        return resumesAPI.create({
          job_id: params.jobId,
          ...params.data,
        });
      }
    },
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ["resumes", variables.jobId] });
      queryClient.invalidateQueries({ queryKey: ["jobs", variables.jobId] });
    },
  });
}

/**
 * Hook to pin a resume version.
 */
export function usePinResumeVersion() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (params: { jobId: number; versionId: number }) => {
      return resumesAPI.pinVersion(params.versionId);
    },
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ["resumes", variables.jobId] });
      queryClient.invalidateQueries({ queryKey: ["jobs", variables.jobId] });
    },
  });
}

/**
 * Hook to unpin the canonical resume for a job.
 */
export function useUnpinResume() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (params: { jobId: number }) =>
      resumesAPI.getCurrent(params.jobId).then((resume) =>
        resumesAPI.unpinVersion(resume.id)
      ),
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ["resumes", variables.jobId] });
      queryClient.invalidateQueries({ queryKey: ["jobs", variables.jobId] });
    },
  });
}

/**
 * Hook to compare two resume versions.
 */
export function useCompareResumeVersions() {
  return useMutation({
    mutationFn: (params: {
      jobId: number;
      version1Id: number;
      version2Id: number;
    }) =>
      resumesAPI.compareVersions(
        params.jobId,
        params.version1Id,
        params.version2Id
      ),
  });
}
