# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
# Generated by: prompts sync
# To update: run `python cli.py prompts sync`

from enum import Enum


class PromptName(Enum):
    """Enum of available prompts in the /prompts directory."""

    EXTRACT_EXPERIENCE_UPDATES = "extract_experience_updates"
    GAP_ANALYSIS = "gap_analysis"
    RESUME_ALIGNMENT_WORKFLOW = "resume_alignment_workflow"
    STAKEHOLDER_ANALYSIS = "stakeholder_analysis"
