// Shared application types
// This file will contain TypeScript types that are shared across the application
// and are not generated from the database schema

// Re-export commonly used types from the database package for convenience
export type {
  Job,
  JobInsert,
  JobUpdate,
  JobStatus,
  Experience,
  ExperienceInsert,
  ExperienceUpdate,
  Achievement,
  AchievementInsert,
  AchievementUpdate,
  Education,
  EducationInsert,
  EducationUpdate,
  Certification,
  CertificationInsert,
  CertificationUpdate,
  User,
  UserInsert,
  UserUpdate,
  Resume,
  ResumeInsert,
  ResumeUpdate,
  ResumeVersion,
  ResumeVersionInsert,
  ResumeVersionUpdate,
  CoverLetter,
  CoverLetterInsert,
  CoverLetterUpdate,
  CoverLetterVersion,
  CoverLetterVersionInsert,
  CoverLetterVersionUpdate,
  Note,
  NoteInsert,
  NoteUpdate,
  ExperienceProposal,
  ExperienceProposalInsert,
  ExperienceProposalUpdate,
  JobIntakeSession,
  JobIntakeSessionInsert,
  JobIntakeSessionUpdate,
  Template,
  TemplateInsert,
  TemplateUpdate,
  // Resume JSON data types
  ResumeData,
  ResumeExperience,
  ResumeEducation,
  ResumeCertification,
} from "@resume/database/types";
