"""Sync OpenRouter models and generate enum."""

from __future__ import annotations

import os
import re

import requests

from .constants import OPENROUTER_API_URL, SRC_DIR


def fetch_models() -> list[dict[str, str]]:
    """Fetch available models from OpenRouter API.

    Requires OPENROUTER_API_KEY environment variable to be set.

    Returns:
        List of model dictionaries with id, name, and description fields.

    Raises:
        ValueError: If API call fails or response is malformed.
    """
    api_key = os.environ.get("OPENROUTER_API_KEY")
    if not api_key:
        raise ValueError("OPENROUTER_API_KEY environment variable is not set.")

    headers = {"Authorization": f"Bearer {api_key}"}

    try:
        response = requests.get(OPENROUTER_API_URL, headers=headers, timeout=30)
        response.raise_for_status()
    except requests.RequestException as e:
        raise ValueError(
            f"Failed to fetch models from OpenRouter: {e}\n"
            "Suggestions:\n"
            "  - Check your OPENROUTER_API_KEY environment variable\n"
            "  - Verify your network connection\n"
            "  - Ensure the OpenRouter API is accessible"
        ) from e

    try:
        data = response.json()
        models = data.get("data", [])
    except (ValueError, KeyError) as e:
        raise ValueError(f"Failed to parse OpenRouter API response: {e}") from e

    if not isinstance(models, list):
        raise ValueError("OpenRouter API returned unexpected data structure")

    # Validate and normalize model data
    normalized_models = []
    for model in models:
        if not isinstance(model, dict):
            continue

        model_id = model.get("id")
        if not model_id:
            continue

        normalized_models.append({
            "id": model_id,
            "name": model.get("name", "Unknown"),
            "description": model.get("description", "No description available"),
        })

    if not normalized_models:
        raise ValueError("No valid models returned from OpenRouter API")

    return normalized_models


def generate_models_file(models: list[dict[str, str]]) -> int:
    """Generate src/shared/model_names.py with Models enum.

    Args:
        models: List of model dictionaries with id, name, and description.

    Returns:
        Number of models generated.
    """
    output_path = SRC_DIR / "shared" / "model_names.py"

    lines = [
        "# " + "=" * 78,
        "# AUTO-GENERATED FILE - DO NOT MANUALLY EDIT",
        "# " + "=" * 78,
        "#",
        "# This file is automatically generated by the OpenRouter models sync command.",
        "# To update this file, run:",
        "#",
        "#     python -m tools models sync",
        "#",
        "# This command fetches the latest available models from OpenRouter and",
        "# regenerates this enum with all available models.",
        "# " + "=" * 78,
        "",
        "from __future__ import annotations",
        "",
        "from enum import Enum",
        "",
        "",
        "class ModelName(str, Enum):",
        '    """Available models from OpenRouter."""',
        "",
    ]

    # Sort models by their sanitized enum key for easy lookup
    models_with_keys = []
    for model in models:
        enum_key = sanitize_enum_key(model["id"])
        models_with_keys.append((enum_key, model))

    models_with_keys.sort(key=lambda x: x[0])

    # Generate enum members in alphabetical order
    for enum_key, model in models_with_keys:
        model_id = model["id"]
        name = model["name"].strip()
        description = model["description"].strip()

        # Add enum member
        lines.append(f'    {enum_key} = "{model_id}"')

        # Add docstring with proper line handling
        docstring = f'    """{name} - {description}"""'
        # Strip trailing whitespace from each line in case description has newlines
        docstring_lines = [line.rstrip() for line in docstring.split("\n")]
        lines.extend(docstring_lines)

        lines.append("")

    # Write to file
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")

    return len(models_with_keys)


def sanitize_enum_key(model_id: str) -> str:
    """Convert a model ID to a valid Python enum key.

    Args:
        model_id: The model ID from OpenRouter (e.g., "openai/gpt-4o")

    Returns:
        A valid Python enum key (e.g., "OPENAI__GPT_4O")
    """
    # Convert to uppercase
    key = model_id.upper()

    # Replace forward slash with double underscore
    key = key.replace("/", "__")

    # Replace hyphens, spaces, and other special characters with single underscores
    key = re.sub(r"[^A-Z0-9_]", "_", key)

    # Remove consecutive duplicate underscores (3+ in a row), preserving double underscores from slashes
    key = re.sub(r"_{3,}", "_", key)

    # Remove leading/trailing underscores
    key = key.strip("_")

    # Prefix with m_ if starts with digit
    if key and key[0].isdigit():
        key = f"m_{key}"

    return key
