"""Enum generation for prompt names."""

from __future__ import annotations

from pathlib import Path

from .constants import PROMPTS_DIR


def generate_prompt_enum() -> int:
    """Generate the PromptName enum from files in the prompts directory.

    Returns:
        Number of prompt enum members generated
    """
    # Scan prompts directory
    prompt_files = sorted(PROMPTS_DIR.glob("*.json"))

    # Generate enum members (create empty enum if no prompts found)
    enum_members = []
    for prompt_file in prompt_files:
        # Convert filename to enum member name (uppercase with underscores)
        name = prompt_file.stem  # Remove .json extension
        enum_name = name.upper()
        enum_members.append(f'    {enum_name} = "{name}"')

    # Generate enum file content
    if enum_members:
        enum_body = "\n".join(enum_members)
    else:
        # Create empty enum with a pass statement
        enum_body = "    pass"

    enum_content = f'''# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
# Generated by: prompts sync
# To update: run `python cli.py prompts sync`

from enum import Enum


class PromptName(Enum):
    """Enum of available prompts in the /prompts directory."""

{enum_body}
'''

    # Write to file
    enum_file = Path("src/core/prompts/names.py")
    enum_file.parent.mkdir(parents=True, exist_ok=True)
    enum_file.write_text(enum_content, encoding="utf-8")

    return len(enum_members)
