# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
# Generated by: prompts sync
# To update: run `python cli.py prompts sync`

from __future__ import annotations

from collections.abc import Sequence
from typing import TypedDict

from langchain_core.messages import BaseMessage


class ExtractExperienceUpdatesInput(TypedDict):
    """Input variables for extract_experience_updates prompt template."""

    chat_history: Sequence[BaseMessage]
    work_experience: str


class GapAnalysisInput(TypedDict):
    """Input variables for gap_analysis prompt template."""

    job_description: str
    work_experience: str


class ResumeAlignmentWorkflowInput(TypedDict):
    """Input variables for resume_alignment_workflow prompt template."""

    gap_analysis: str
    job_description: str
    message_history: Sequence[BaseMessage]
    stakeholder_analysis: str
    work_experience: str


class StakeholderAnalysisInput(TypedDict):
    """Input variables for stakeholder_analysis prompt template."""

    job_description: str
    work_experience: str

